import 'dart:convert';

/// Status of the PC pairing/session lifecycle on the Android side.
enum PcSessionStatus {
  idle,
  connecting,
  paired,
  sessionStarted,
  sessionComplete,
  sessionFailed,
  disconnected,
}

/// Parsed payload from the QR code generated by the PC app.
///
/// Expected JSON format:
/// ```json
/// { "ip": "192.168.1.100", "port": 8765, "token": "hmac_token", "expires_at": 1234567890000 }
/// ```
class PcQrPayload {
  final String ip;
  final int port;
  final String token;
  final int expiresAt; // unix ms

  const PcQrPayload({
    required this.ip,
    required this.port,
    required this.token,
    required this.expiresAt,
  });

  factory PcQrPayload.fromJson(Map<String, dynamic> json) {
    return PcQrPayload(
      ip: json['ip'] as String,
      port: json['port'] as int,
      token: json['token'] as String,
      expiresAt: json['expires_at'] as int,
    );
  }

  factory PcQrPayload.fromRawString(String raw) {
    return PcQrPayload.fromJson(jsonDecode(raw) as Map<String, dynamic>);
  }

  bool get isExpired =>
      DateTime.now().millisecondsSinceEpoch > expiresAt;

  /// WebSocket URL for Android to connect to PC's local server.
  String get wsUrl => 'ws://$ip:$port';
}

/// Represents a message received from (or sent to) the PC over the local WS.
///
/// Incoming types (PC → Android):
///   pair_confirmed, session_started, session_complete, session_failed, heartbeat_pong, error
///
/// Outgoing types (Android → PC):
///   pair_request, heartbeat_ping
class PcMessage {
  final String type;
  final Map<String, dynamic> payload;

  const PcMessage({required this.type, this.payload = const {}});

  factory PcMessage.fromJson(Map<String, dynamic> json) {
    final type = json['type'] as String? ?? 'unknown';
    final payload = Map<String, dynamic>.from(json)..remove('type');
    return PcMessage(type: type, payload: payload);
  }

  // ── Outgoing message builders ──

  /// Sent after connecting — authenticates Android user and provides workout config.
  static String buildPairRequest({
    required String jwt,
    required String workoutId,
    required String exerciseType,
  }) {
    return jsonEncode({
      'type': 'pair_request',
      'jwt': jwt,
      'session_config': {
        'workout_id': workoutId,
        'exercise_type': exerciseType,
      },
    });
  }

  /// Sent every 5 seconds while session is active.
  static String buildHeartbeatPing() =>
      jsonEncode({'type': 'heartbeat_ping'});
}
