// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'onboarding_state.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$OnboardingStateImpl _$$OnboardingStateImplFromJson(
  Map<String, dynamic> json,
) => _$OnboardingStateImpl(
  userId: json['userId'] as String?,
  email: json['email'] as String?,
  fullName: json['fullName'] as String?,
  phone: json['phone'] as String?,
  token: json['token'] as String?,
  patientFullName: json['patientFullName'] as String?,
  patientPhone: json['patientPhone'] as String?,
  createdPatientId: json['createdPatientId'] as String?,
  painLocation: json['painLocation'] as String?,
  painScaleScore: (json['painScaleScore'] as num?)?.toInt(),
  painCharacter: json['painCharacter'] as String?,
  painAssessment: json['painAssessment'] as String?,
  muscleTone: json['muscleTone'] as String?,
  muscleStrength: json['muscleStrength'] as String?,
  balancedValuation: json['balancedValuation'] as String?,
  fallRisk: json['fallRisk'] as String?,
  selfStandAbility: json['selfStandAbility'] as String?,
  tugTime: (json['tugTime'] as num?)?.toInt(),
  previousIllness: json['previousIllness'] as String?,
  previousTreatments: json['previousTreatments'] as String?,
  dailyActivities: json['dailyActivities'] as String?,
  doctorRecommended: json['doctorRecommended'] as String?,
  doctorTreatmentPlan: json['doctorTreatmentPlan'] as String?,
  note: json['note'] as String?,
  gender: json['gender'] as String?,
  livingArrangement: json['livingArrangement'] as String?,
  bmiScore: (json['bmiScore'] as num?)?.toDouble(),
  mapScore: (json['mapScore'] as num?)?.toInt(),
  rhrScore: (json['rhrScore'] as num?)?.toInt(),
  bloodGlucoseLevel: (json['bloodGlucoseLevel'] as num?)?.toInt(),
  adlScore: (json['adlScore'] as num?)?.toInt(),
  iadlScore: (json['iadlScore'] as num?)?.toInt(),
  diseaseType: json['diseaseType'] as String? ?? 'PHYSICAL_THERAPY',
  conditionNote: json['conditionNote'] as String?,
  isLoading: json['isLoading'] as bool? ?? false,
  currentStep: (json['currentStep'] as num?)?.toInt() ?? 1,
);

Map<String, dynamic> _$$OnboardingStateImplToJson(
  _$OnboardingStateImpl instance,
) => <String, dynamic>{
  'userId': instance.userId,
  'email': instance.email,
  'fullName': instance.fullName,
  'phone': instance.phone,
  'token': instance.token,
  'patientFullName': instance.patientFullName,
  'patientPhone': instance.patientPhone,
  'createdPatientId': instance.createdPatientId,
  'painLocation': instance.painLocation,
  'painScaleScore': instance.painScaleScore,
  'painCharacter': instance.painCharacter,
  'painAssessment': instance.painAssessment,
  'muscleTone': instance.muscleTone,
  'muscleStrength': instance.muscleStrength,
  'balancedValuation': instance.balancedValuation,
  'fallRisk': instance.fallRisk,
  'selfStandAbility': instance.selfStandAbility,
  'tugTime': instance.tugTime,
  'previousIllness': instance.previousIllness,
  'previousTreatments': instance.previousTreatments,
  'dailyActivities': instance.dailyActivities,
  'doctorRecommended': instance.doctorRecommended,
  'doctorTreatmentPlan': instance.doctorTreatmentPlan,
  'note': instance.note,
  'gender': instance.gender,
  'livingArrangement': instance.livingArrangement,
  'bmiScore': instance.bmiScore,
  'mapScore': instance.mapScore,
  'rhrScore': instance.rhrScore,
  'bloodGlucoseLevel': instance.bloodGlucoseLevel,
  'adlScore': instance.adlScore,
  'iadlScore': instance.iadlScore,
  'diseaseType': instance.diseaseType,
  'conditionNote': instance.conditionNote,
  'isLoading': instance.isLoading,
  'currentStep': instance.currentStep,
};
